name: Deploy Docker Image to EC2

on:
  workflow_run:
    workflows: [Build and Push Docker Image]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} #CI 성공 시 실행

    steps:
      - name: Connect and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo " >>> Pull latest image from Docker Hub"
            docker pull ${{ secrets.DOCKER_USERNAME }}/lotter-java21-demo:latest
            
            echo " >>> Stop old container"
            docker stop lotter || true
            docker rm lotter || true
            
            echo " >>> Start new container"
            docker run -d -p 8080:8080 --name lotter ${{ secrets.DOCKER_USERNAME }}/lotter-java21-demo:latest
            
            echo "Deploy Complete"
